### ISSUE TITLE
has no attribute 'set_data_loader'

### ISSUE THREAD

**Issue by chenyonx** [ownstyledu/Translate-to-Recognize-Networks#2]
hello ,when i want to run the evalute.py,it's report has no attrbuite "set_data_loader",then,i click into "TRecgNet_Upsample_Resiual",i am also cann't find .could you tell me how to solve it?(我是中国的学生)

**Comment by chenyonx** [comment]
可以中文交流

**Comment by ownstyledu** [comment]
你好，谢谢关注。这个文件可能经过几次重构以后也没维护。平时训练的时候，把配置文件里面evaluate这个参数设置为True，每轮迭代结束后就会去验证一下测试集，因为也没有划分验证集，所以就跟evaluate得到的效果一样～还有其他问题欢迎咨询～

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Learning bird "<notifications@github.com>;
发送时间：2019年9月11日(星期三) 下午3:20
收件人："ownstyledu/Translate-to-Recognize-Networks" <Translate-to-Recognize-Networks@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：Re: [ownstyledu/Translate-to-Recognize-Networks] has no attribute 'set_data_loader' (#2)
-----------------------------------

 
可以中文交流

**Comment by chenyonx** [comment]
所以也就是说每次训练后的准确率结果就是在测试集测试后的结果是吗？

**Comment by ownstyledu** [comment]
是的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Learning bird "<notifications@github.com>;
发送时间：2019年9月11日(星期三) 下午3:36
收件人："ownstyledu/Translate-to-Recognize-Networks" <Translate-to-Recognize-Networks@noreply.github.com>;
抄送："ownstyledu "<dudp.nju@gmail.com>;"Comment "<comment@noreply.github.com>;
主题：Re: [ownstyledu/Translate-to-Recognize-Networks] has no attribute 'set_data_loader' (#2)
-----------------------------------

 
所以也就是说每次训练后的准确率结果就是在测试集测试后的结果是吗？

**Comment by chenyonx** [comment]
好的，谢谢
