### ISSUE TITLE
How to train TrecgNet model with data augmentation?

### ISSUE THREAD

**Issue by CongFang** [ownstyledu/Translate-to-Recognize-Networks#4]
我将use_fake设置为True以后，会报如下错误：
TypeError: define_TrecgNet() got an unexpected keyword argument 'use_noise'
于是将trecg_model.py中的代码：
sample_model = networks.define_TrecgNet(cfg_sample, use_noise=not self.use_noise, upsample=True, device=self.device)
改为：
sample_model = networks.define_TrecgNet(cfg_sample, upsample=True, device=self.device)
所以，use_noise这个参数不能使用吗？谢谢。

**Comment by ownstyledu** [comment]
你好，这个应该是历史代码没及时更新导致的，现在最新的代码已经用不到这个参数了，我们最新实验发现只要把upsample的norm设置为Instancenorm，加不加这个noise其实对最后结果没有特别大的影响，所以遇到跟这个参数相关的都可以自己改一下不用就行了

**Comment by CongFang** [comment]
好的，谢谢解答！
