### ISSUE TITLE
 i use resnet18 to train the split image dataset  directly

### ISSUE THREAD

**Issue by chenyonx** [ownstyledu/Translate-to-Recognize-Networks#5]
hello ， i use resnet18 to train the split  rgb image dataset  directly， the result is 57.43%,even higer  than use your way,is there me have problem? Or differently with you?

**Comment by chenyonx** [comment]
the baseline is 47.4%，but my result is 57.34%

**Comment by ownstyledu** [comment]
I think the result you report might be ///accuracy///, not the ///mean accuracy///
